### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by petk** [symfony-si/symfony-must-watch#1]
- [x] Reduce a list of videos to a must watch instead of a current full list
- [x] Fix author names where missing
- [x] Add must watch Screenfony tutorials
